{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Risks",
        "Service": "/RisksMobile/Services/service1.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "title": "#Control:title/#Value",
        "prio": "#Control:prio/#Value",
        "impact": "#Control:impact/#Value",
        "criticality": "#Control:criticality/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/RisksMobile/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/RisksMobile/Actions/UpdateEntityFailureMessage.action"
}